### ISSUE TITLE
Access AWS S3 `naip-visualization` bucket files with `gdalinfo`

### ISSUE THREAD

**Issue by ViswanathB** [awslabs/open-data-docs#23]
**Description:**

This issue is for `https://github.com/awslabs/open-data-docs/tree/main/docs/naip`
I am trying to make use of this open source imagery for one of my applications but hitting the following issue when trying to build a vrt file for naip-visualization imagery.

I built `vrt` file for AR(attached an example for 2012) (s3://naip-visualization/ar/) for all the years successfully and was able to access the files using `rasterio` without any issue(attached under the name ri_2012.log)
![Screenshot from 2023-02-24 15-44-01](https://user-images.githubusercontent.com/8933547/221287775-1db6e60f-0256-4239-b099-008d8321a62a.png)

**Problem**:
But I cannot seem to access these tif files with `gdalinfo` (https://gdal.org/programs/gdalinfo.html). I uploaded a `.tif` file to personal s3 bucket and was able to do this which means it is not the problem with the tool.
![Screenshot from 2023-02-24 15-51-26](https://user-images.githubusercontent.com/8933547/221289100-d4b3c29d-156e-42e8-880a-b763a2436623.png)

**Queries for resolution**:
Since this is a public bucket - is this restricted? If there is a way to access it similarly, it helps with
1. recursively fetching the information for files 
2. Can I use `gdalbuildvrt` (https://gdal.org/programs/gdalbuildvrt.html) or something similar on this bucket to generate .vrt file? 
  

[ri_2012.log](https://github.com/awslabs/open-data-docs/files/10828614/ri_2012.log)

**Comment by jeffejefe** [comment]
@ViswanathB since this is a requester pays bucket so you need to make sure that AWS_REQUEST_PAYER is enabled per http://www.gdal.org/gdal_virtual_file_systems.html#gdal_virtual_file_systems_vsis3 

So in your session you need to make sure you pass the export AWS_REQUEST_PAYER=requester then you can run gdalinfo /vsis3/naip-visualization/al/2013/100cm/rgb/30085/m_3008501_ne_16_1_20130928.tif

Once you pass your AWS credentials you should be able to access the files.

**Comment by ViswanathB** [comment]
Thanks @jeffejefe This seems to be working.
